DROP TABLE IF EXISTS sets CASCADE;

CREATE TABLE sets (
  id SERIAL PRIMARY KEY NOT NULL,
  number INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  image_url VARCHAR(255),
  url VARCHAR(255),
  category VARCHAR(255)
)